### ISSUE TITLE
execuse,I encounter some data issues

### ISSUE THREAD

**Issue by solitudetuzi** [KevinMenden/scaden#102]
I'm learning to use scaden，and I ran into some difficulties running programs and reference papers, and I couldn't find some of the prediction data （samples.txt）and their lable.txt.
with regard to pancreatic cell data, I found the ****pancreas.h5ad**** file and the **xin_bulk_labels.txt** (I don't know if the true mark of the predicted data found is correct), but I didn't find the input file for the prediction###  xin_bulk_labels.txt , which is the xin_bulk_samples.txt file.
I have send you an email. 
I am so sorry for interrupt you,and want to learn Scaden.
without your help,I can not continue my study.

**Comment by KevinMenden** [comment]
Hi,

I'm not sure I understand fully what your goal is or what you need exactly.
The Pancreas datasets are all scRNA-seq datasets, and for the bulk labels, those are just the fractions of cell types per samples. As bulk you have to use the merged cells for the different samples in this case.

Best,
Kevin
