### ISSUE TITLE
The simulated training dataset for the Human Brain.

### ISSUE THREAD

**Issue by hathawayxxh** [KevinMenden/scaden#104]
Hi Kevin,

I am trying to reimplement the experiments in your paper. However, I didn't find the simulated training data for the human brain in the following url:
https://scaden.readthedocs.io/en/latest/datasets.html 
Could you release the simulated dataset so I can conduct the experiments?

Thank your so much.

Best regards,
Xiaohan

**Comment by Tushar-87** [comment]
I am also interested in human brain single cell data...

**Comment by KevinMenden** [comment]
Hi,

yes unfortunately we didn't publish them on Figshare. I will see if can make a new dataset and publish it there or, alternatively, publish the scripts for creating it from scratch. I currently don't have much time to maintain Scaden but hopefully I can do this rather soon.

Best,
Kevin

**Comment by hathawayxxh** [comment]
Hi Kevin,

It would be great if you could publish the scripts for creating the dataset. 
BTW, I am also curious about the single cell annotation part. Since the raw data you downloaded is not annotated, so you first clustered the cells and then annotated the cells by gene markers. Could you also publish the scripts for this cell annotation part?

Best,
Xiaohan

**Comment by KevinMenden** [comment]
Hi Both,

have a look here: https://figshare.com/projects/Scaden/62834

This contains the scripts used to generate some of the datasets. Look in the `preprocessing` folder. There should be a script for every dataset used (you just need to download them). Those scripts contain the cell type annotation and generation of processed datasets, which can then be used with `scaden simulate` to make your own datasets.

Hope that helps!

Cheers,
Kevin

**Comment by hathawayxxh** [comment]
Hi Kevin,

Thanks but I cannot find the "preprocessing" folder in the scripts.

![image](https://user-images.githubusercontent.com/27730257/127814922-448c20e2-56f1-48b3-9f1e-92457e5ac3f0.png)

**Comment by hathawayxxh** [comment]
Do you mean this folder?
![image](https://user-images.githubusercontent.com/27730257/127815445-4c48361c-84db-44d9-bc15-801a0751e385.png)

**Comment by KevinMenden** [comment]
Sorry, yes that's the correct folde! :+1:
