### ISSUE TITLE
Is it wrong to deconvolute bulk RNA seq data of a tissue using scRNAseq data of a different tissue?

### ISSUE THREAD

**Issue by Tushar-87** [KevinMenden/scaden#105]
I am interested in knowing if PBMCs infiltrate into the brain. I want to deconvolute bulk RNA seq data of human brain using single cell data of human PBMCs. Does it make sense to do this? 
One more issue, it is taking forever to finish deconvolution in a webtool. Earlier it used to be much faster. Now the job is running since a day and still it is not finished.

**Comment by KevinMenden** [comment]
Hi,
well you can try it out but I wouldn't be sure how to interpret the results. You would basically be training and predicting on completely different data distributions. So in short, Scaden was not build for this case.

I'm not maintaing the web tool so can't comment on that (maybe @zeehio can). But you should be able to use the standalone version instead.

**Comment by Tushar-87** [comment]
Thanks a lot for clarifying this Kevin. I was wondering what if: I add human PMBC single cell data to human single cell brain data (simple merging, no data set integration) and use this merged data set for training and prediction? It will be great to have your expert opinion on this.

**Comment by KevinMenden** [comment]
Yes that could work. However, I have not tested this and so I cannot tell you if it works and how good :) 
I imagine that PBMCs that infiltrate the brain have a differente transcriptome than other PBMCs. Anyway to a certain extent it should work I guess!
