### ISSUE TITLE
issues with conda version of scaden

### ISSUE THREAD

**Issue by me37uday** [KevinMenden/scaden#107]
Hi :)

I have been trying to use Scaden lately and I ran into a number of things. A tool like scaden which may need a minimum RAM of 16GB is usually used on a cluster, where majority of the users would not have the root privilege. So I personally insist the developer to mention all the dependencies required by the tool. How to use the tool is pretty well documented but not how to install it and other requirements. So long story short I managed to install it using conda and scaden example doesn't seem to work (needed to understand the basic input format to the tool). I get the following response :

```
(scaden) urangasw@valis:~/scaden_example$ scaden example
/home/urangasw/miniconda3/envs/scaden/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:455: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/urangasw/miniconda3/envs/scaden/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:456: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/urangasw/miniconda3/envs/scaden/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:457: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/urangasw/miniconda3/envs/scaden/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/urangasw/miniconda3/envs/scaden/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/urangasw/miniconda3/envs/scaden/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:462: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/urangasw/miniconda3/envs/scaden/lib/python3.6/site-packages/anndata/core/anndata.py:17: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex

     ____                _            
    / ___|  ___ __ _  __| | ___ _ __  
    \___ \ / __/ _` |/ _` |/ _ \ '_ \ 
     ___) | (_| (_| | (_| |  __/ | | |
    |____/ \___\__,_|\__,_|\___|_| |_|

    
Usage: scaden [OPTIONS] COMMAND [ARGS]...
Try 'scaden --help' for help.

Error: No such command 'example'.

```
Please let me know how I can go about it, be it using pip or conda and the respective versions of various dependencies that scaden is compatible with.

**Comment by KevinMenden** [comment]
Hi @me37uday ,

Scaden actually doesn't need a lot of resources, and 16 GB should be more than enough in most cases. Most modern workstations/laptops that are used for bioinformatics should have enough power.

Every dependency of Scaden is listed in the `setup.py` file, if you want to install them manually.

I think there is documentation for installation, you can just use `pip` or `conda`, both should hopefully work (at least on Linux).
I recommend using some form of environments. In your case you seem to have installed an older version of Scaden which lacks the `scaden example` command.

By the way, there is also a Docker container you could use. So plenty of options :-) 
Let me know if that helps!

Cheers,
Kevin

**Comment by me37uday** [comment]
Thanks for your response :)

Is conda version of Scaden working? I am using a Linux machine as well. I created a conda environment with python 3.6.13 and used the command conda install -c bioconda scaden and the above version was installed.

Should I mention the scaden version to be installed in the above mentioned conda command? Please let me know :)

Thanks,
Uday

**Comment by me37uday** [comment]
Hi @KevinMenden ,

Thanks for your response.

I got it working by simply using pip :)

The procedure and command was as follows : 

1. created a conda environment with specific python version using  : 
 
`conda create -n scaden python=3.9 `

2. installed pip in the environment (if need be)

`conda install pip`

3. installed scaden using : 

`pip install scaden==1.1.2`

scaden example is working as mentioned in the manual :)

Thanks,
Uday

**Comment by KevinMenden** [comment]
Cool, nice to see that you got it working!

I did experience some issues with installing from conda in the past but couldnt pinpoint the issue. Pip is the easiest way indeed 👍
