### ISSUE TITLE
Scaden example command not found

### ISSUE THREAD

**Issue by bio-visualisation** [KevinMenden/scaden#110]
@KevinMenden I tried to generate example data but it is showing Error: No such command 'example'. Please help

**Comment by KevinMenden** [comment]
Hi @bio-visualisation ,

how did you install Scaden and which version are you using?
The `scaden example` command was added later, so earlier versions don't have it.

I recommend trying to install a newer version - should be possible both with pip and conda!

**Comment by bio-visualisation** [comment]
Initially I installed scaden with the following command:
$ conda install -c bioconda scaden
Which installed the older version 0.9.4
Later I installed the newer version using $ conda install scaden=1.1.2
Now example command is working. Thank you so much.

**Comment by KevinMenden** [comment]
Awesome :) :+1:
