### ISSUE TITLE
ovarian cancer ascites sample

### ISSUE THREAD

**Issue by HelloYiHan** [KevinMenden/scaden#112]
Hi, Kevin
Thank you for your excellent work.
The scRNA-seq ascites samples (Schelker et al.) were ovarian cancer ascites samples. I was wondering if the Human Ascites dataset (https://scaden.ims.bio/dashboard) could be used on ovarian cancer ascites samples or normal ascites samples? 

Best,
Yi

**Comment by KevinMenden** [comment]
Hi @HelloYiHan ,

Scaden (or any deconvolution tool) will always perform best when the training data is as close as possible to the target data. 
So in this case you would use it on your own risk - I'm not an expert on these tissues and unfortunately can't tell you how good Scaden would perform in this case. You could do a quick run and see whether to results make any sense to get an idea whether this is feasible or not.

Hope that helps a bit!
Best,
Kevin
