### ISSUE TITLE
Scaden web interface sign-in is down

### ISSUE THREAD

**Issue by yunners** [KevinMenden/scaden#117]
Cannot sign in with existing account or register a new one. Tried on multiple browsers.

**Comment by KevinMenden** [comment]
Hi @yunners ,

sorry, I'm not maintaining the web interface, and so I'm not sure what's going on there.
I would recommend to just use the standalone application instead!

@zeehio is the web-interface still up and running?

**Comment by zeehio** [comment]
I'll try to figure out what is going on next week.
