### ISSUE TITLE
Scaden simulate, data input

### ISSUE THREAD

**Issue by gemmabb** [KevinMenden/scaden#121]
Hi! 

First of all, thanks for sharing your work :) 
According to the documentation, when simulating the data from our single-cell dataset, we should normalize these counts by the library size. However, the example counts file I see is not strictly normalized, so I was wondering if a strict normalization (i.e., dividing the raw counts by the sum for that sample) would work, since these data would only contain values from 0 to 1. 

Thank you so much in advance!

**Comment by KevinMenden** [comment]
Hi!

Sorry for the late reply!
The counts are normalized exactly to this range inside Scaden's processing scheme, with a normalization method chosen for this. So while you could normalize your counts to 0-1 and it would probably still work, I wouldn't advice doing that.

Hope that answers your question?

Cheers,
Kevin

**Comment by gemmabb** [comment]
Yes! It does answer it!

Thank you so much,

Gemma

**Comment by gemmabb** [comment]
Sorry to bother you again... Our single cell data should anyway be library normalized before using **scaden simulate**, shouldn't it? I think you were using scanpy to get your single cell data library normalized counts but instead of being summed to 1, they added to the median of the library size before normalization. Am I right?
