### ISSUE TITLE
Variance cut-off in get_signature_genes( )

### ISSUE THREAD

**Issue by RHReynolds** [KevinMenden/scaden#16]
Hi Kevin,

Firstly, thanks for developing the package! The underlying concept is very cool.

Secondly, this is less of an issue and more of a heads-up. I've been working through your usage documentation in an attempt to apply scaden to my own data. One bug I ran in to while running through the workflow was during the `scaden process` step. It turns out that one of the functions `get_signature_genes( )` filters prediction samples by their within-gene variance (`data.var(axis=1) > var_cutoff`, where `var_cutoff` is set to 0.1 by default). As I was using normalised counts (raw counts/total library size)  in my bulk data, which has been sequenced to a very high depth, the resulting within-gene variances I got were tiny and much smaller than the cut-off. For this reason, no common genes were found between my training data and prediction data and `scaden process` didn't run. Once I scaled my normalised counts by multiplying by 10,000 I had no problem. It might be worth pointing this out to future users who might run into a similar issue.

All the best,
Regina

**Comment by KevinMenden** [comment]
Hi Regina,

thanks for pointing this out!
I'll definitely change this. The main point of this small filtering step was to cut out genes that are basically almost always zero, or have only very little variance. On the test data, only a few genes were cut out by this, but you are of course right that this depends. I'll add this as a variable for the tool and in the documentation.

Thanks!
And sorry for the late replay, I was on holiday :) 

Best,
Kevin

**Comment by RHReynolds** [comment]
Hi Kevin,

No worries re. response time! Hope it was a good holiday :)
And adding the variance filter as a variable would be great. As you said, you don't want to be including genes with super low/no expression, so it makes sense to keep it and just let users adjust it.

Thanks again for the package!

Best,
Regina

**Comment by KevinMenden** [comment]
#18 solves (among other things) this issue.
