### ISSUE TITLE
Single Cell Expression Matrix

### ISSUE THREAD

**Issue by Prayforhanluo** [KevinMenden/scaden#17]
Hi, kevin
     great work!
     Can you provide the single cell expression matrix? Or they are exist somewhere and I missed.
     All the best
HanLuo

**Comment by KevinMenden** [comment]
Hi HanLuo,

thanks :) 
Of course, all the data is publicly available. Which single cell expression matrix do you need?
The links to all datasets are in the pre-print (under Data Availability): https://www.biorxiv.org/content/10.1101/659227v2
The python scripts I used for processing you can find here: https://figshare.com/projects/Scaden/62834

Let me know if you need anything else.

Best,
Kevin

**Comment by KevinMenden** [comment]
HI HanLuo,

sorry that I didn't reply - something is off with my notifications and I relied on them ...

You'll have to process them yourself - however the scripts I used are on figshare. So basically you'll just have to download the corresponding files on, and use the script for processing. That should give you the same output as I got (provided you use the same software versions).

Best
Kevin
