### ISSUE TITLE
predicting bulk RNA-seq

### ISSUE THREAD

**Issue by jon8991** [KevinMenden/scaden#33]
Hi,

I have trained scaden on a .h5ad file I produced. 

I am looking to run scaden predict on bulk RNA-seq data if possible.
Could you tell me what format the bulk RNA-seq data would need to be in? 

Regards

Jon8991

**Comment by KevinMenden** [comment]
Hi Jon,

sure, please also have a look at the documentation:
https://scaden.readthedocs.io/en/latest/usage/
If you look under 'Usage' and scroll down to file formats, you can find an explanation.

Basically what you need is a tab-separated file with genes as rows and samples as columns. 
The expression values should **not** be on a logarithmic scale.
You can leave the column name for the first row, so your gene names, free - just put a tab in there.
So something like this:
            sample1 sample2 sample 4
gene1      234        34             333
gene1         1            3               3
gene3

Let me know if you get any other issues.

Cheers,
Kevin

**Comment by jon8991** [comment]
Brilliant. 

That helps a great deal. :)
Thank you for the quick reply 

Have a good day

Jon8991
