### ISSUE TITLE
Normalization of input bulk data

### ISSUE THREAD

**Issue by Tushar-87** [KevinMenden/scaden#34]
Hi Kevin
 What kind of normalization of the input bulk data is suitable for SCADEN? Although, normalization to the sequencing depth is most common, isn't normalization to the gene length more appropriate while estimating different cell types which have different marker genes?

**Comment by KevinMenden** [comment]
Hi Tushar,

I have tested different kinds of normalizations, and could not detect a very strong influence on the results.
However, as you have suggested, I would also recommend using a normalization that takes gene length into account. Especially when using reference data from scRNA-seq protocols that use UMIs (like 10X).

Did that answer your question?
Thanks for making an issue by the way :+1:
