### ISSUE TITLE
Recommended #s for cells and # of samples

### ISSUE THREAD

**Issue by rdchow** [KevinMenden/scaden#35]
Hello,

I am wondering if you have specific recommendations for the # of cells to include in each sample, and for how many samples to create? I see the defaults are 100 cells in 8000 samples -- in your experience, is this sufficient for most use-cases? In your manuscript, it looks like you used 500 cells per sample, but the total # of samples seemed to vary quite a bit between datasets.

Thanks for your help!

**Comment by KevinMenden** [comment]
Hi,

sorry for the late replay (holidays). I've tested this to some extend while writing the algorithm, and can say that the effect is actually minor.
As number of cells per sample I would stick between 100 and maybe 500, as you wrote. That's what I tested and should work fine for most datasets. Of course, if it is a dataset with tons of cells, you can use more. If it only has, say, 1000 cells, obviously you shouldn't use 500.

As for the number of samples, I've made some testing, and you should find the results in the supplements. In short, the performance of Scaden starts to saturate already at about 1000-2000 samples, but still increases slightly if you add more samples. So it just depends on how big of a dataset you want to build :-) 

Let me know if that answered your questions!

**Comment by rdchow** [comment]
Hello,

Thank you so much, that answers my questions!
