### ISSUE TITLE
issues with the webtool

### ISSUE THREAD

**Issue by liu-ying-jun** [KevinMenden/scaden#42]
Hi Kevin

I am trying out the Scaden webtool currently. The demo run works well. However, when I run the webtool with my own data, it gives an error saying Error preparing job directories and files.  Do you know where the problem might be? thanks for your help. 

Best,
Yingjun

**Comment by KevinMenden** [comment]
Hi Yingjun,

thanks for reporting this issue.

@zeehio could you have a look at this?

**Comment by zeehio** [comment]
Hi @liu-ying-jun 

I was able to find the traceback in the logs.

Currently the web tool is a bit picky with the format of the input data:

The header of the bulk rna file should have the sample names. For the first column, which contains the gene names, there should be no name in the header. Specifically, what we expect is: `[TAB]name-of-sample1[TAB]name-of-sample2[TAB]name-of-sample3`. Note how the first column does not have a name, so the file starts with a `[TAB]` character. I saw that your file starts with `"	"[TAB]name-of-sample1[TAB]name-of-sample2`... 

Could you try removing the leading `"	"` in your input file?

**Comment by liu-ying-jun** [comment]
thanks, zeehio,

I have made some tests, which were inspired by your answer. I found "  " as the column name of the gene list in my input data was not the real issue. The real issue was that there was somehow a missing value in the first column (the gene list) of my input data. when I removed the row containing this missing value from my input data, the webtool worked no matter the first column name is "  " or leaving empty!

I think it might be helpful for others if you add this information (missing values in the first column) in your instructions on preparing the input file. Of course, before that you may want to test it yourself.

**Comment by KevinMenden** [comment]
Thanks for reporting that!

It's a good point - we'll certainly add this to the documentation to make it more clearer.

**Comment by KevinMenden** [comment]
This will be addressed when fixing the issue #44
