### ISSUE TITLE
PBMC2 (monaco) dataset in pbmc_data.h5ad

### ISSUE THREAD

**Issue by mjjeon** [KevinMenden/scaden#43]
Hello, I downloaded pbmc_data.h5ad and it has 4 simulated datasets and 2 real datasets named sdy67 and GSE65133. 
Could you please also release the PBMC2 dataset in the pbmc_data.h5ad?

Best,
Minji

**Comment by KevinMenden** [comment]
HI Minji, 

could you specify where you downloaded the data from - fighsare?

Best,
Kevin

**Comment by mjjeon** [comment]
Hi Kevin,

Yes I downloaded it from https://figshare.com/s/e59a03885ec4c4d8153f

Best,
Minji

**Comment by KevinMenden** [comment]
Hi Minji,

okay great - I will see whether I have a ready-made h5ad file with the PBMC2 dataset in it and will let you know if so!
Should have time to look after this this afternoon.

Best,
Kevin

**Comment by KevinMenden** [comment]
Hi Minji,

okay I found a dataset containing the data you're looking for in h5ad format. Not sure why it isn't uploaded on figshare ....

Anyway I've sent you a mail with a link! :-)
