### ISSUE TITLE
mouse_brain.h5ad file 

### ISSUE THREAD

**Issue by yunners** [KevinMenden/scaden#58]
Hi there,

I'd like to use the training dataset for the mouse brain to slot into CibersortX as a signature matrix.

I tried opening the .h5ad file in Seurat so I could export the matrix with the phenotype labels (e.g. genes on rows, and cells on columns). But ran into this error:

```
file =  ReadH5AD("C:/Users/James Hong/Desktop/CVT Paper/mouse_brain.h5ad")
Pulling expression matrices and metadata
Data is scaled
Error in ReadH5AD.H5File(file = hfile, assay = assay, layers = layers,  : 
  Seurat requires normalized data present in the raw slot when X is scaled
```
I think the raw slot is missing and only the scaled perhaps SCTransform data is available.

Could you help me with the right .h5ad file or perhaps generate the expression matrix above for CibersortX?

Thanks

**Comment by KevinMenden** [comment]
Hi,

the training data is generated for use with Scaden, hence it is not clear that it will work well with CIBERSORTx. I'm afraid I cannot help you with generating the count matrix ...

If you want to generate training data yourself, have a look at the site of the [Hemberg lab](https://hemberg-lab.github.io/scRNA.seq.datasets/), which provides links to many datasets. 

Good luck!

Kevin
