### ISSUE TITLE
Error: fail to generate example data by using scaden expample

### ISSUE THREAD

**Issue by Zhaohui-Ruan** [KevinMenden/scaden#62]
I want to generate the files "example_counts.txt", "example_celltypes.txt" and "example_bulk_data.txt" in the "example_data" by using scaden example, but an error occurs like the following.

`(lnc) [liziyue@login01 ~]$ scaden example
2020-12-29 01:06:39.852508: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Segmentation fault`

Can anybody give me some advice about this error?
Thanks a lot!

**Comment by KevinMenden** [comment]
Hi!

First things first: which version of Scaden are you using? The ``scaden example` functionality was added only recently.

Is this the only error message you have gotten? I can't really explain this from what I see here ... have you tried more than once?

Kevin

**Comment by Zhaohui-Ruan** [comment]
Thanks for your reply, I have solved this problem. This seems to be due to a conflict between Scaden’s and TensorFlow's versions. An engineer helped me install Scaden, and now I can use it.

**Comment by KevinMenden** [comment]
Great - yes I keep having dependcies issues with TensorFlow every so often ... glad you solved it!
