### ISSUE TITLE
About scaden simulate

### ISSUE THREAD

**Issue by Zhaohui-Ruan** [KevinMenden/scaden#64]
Hi Kevin,

I want to generates 3000 samples of training data. My input is:

```
 scaden simulate --data ./ -n 3000 --pattern "*_counts.txt"
Normal samples: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1500/1500 [02:10<00:00, 11.47it/s]
Sparse samples: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1500/1500 [01:27<00:00, 17.23it/s
```

Is this wrong? I am confused because I did not see the number 3000 appear in the result.

Thank you so much for your help! 
Ruan

**Comment by KevinMenden** [comment]
Hi Ruan,

did you get any errors? If not than this looks good :) 
Scaden generated 1500 normal samples and 1500 sparse samples (those are missing some cell types completely).
If you have a look at the right side of the output, it says two times ``1500/1500``, which basically means it generated 1500 out of 1500 samples.

You have a good point though, that this would be very helpful to mention after creating those samples!
Will leave this issue open and add this to the next release.

Thanks!
Kevin

**Comment by Zhaohui-Ruan** [comment]
Hi Kevin,

I didn't get any errors. I was just confused that there was no number 3000 appear in the result. Thank you for your reply!

Ruan
