### ISSUE TITLE
Scaden test

### ISSUE THREAD

**Issue by Zhaohui-Ruan** [KevinMenden/scaden#65]
Hi Kevin,

I am doing some tests on Scaden. I found that after adding some cells from other sources to the original scRNAseq, the prediction effect will drop a lot. Scaden’s result shows that this kind of cells that shouldn't exist in bulk data exist and some even account for a large proportion. 
In my test, I use PBMC scRNAseq and whole blood bulk RNAseq as the test data. Tumor cells from LUAD (Lung Adenocarcinoma) were added to the PBMC scRNAseq.

Ruan

**Comment by KevinMenden** [comment]
Hi Ruan,

you should only be using the same tissue, as much as possible, for deconvolution.
Here you are essentially mixing three different things:
* PBMC
* whole blood
* LUAD

All of these consist of different celltypes, in the case of the lung adenocarcinoma it is even a very large difference. Scaden wasn't constructed for these cases, as good performance dependes on training and testing data having similar distributions.
So I'm not really surprised that it doesn't work well in those cases.

If you have to perform this deconvolution, I think there are some deconvolution algorithms specializing on immune cells, those might perform better in this scenario, although I can't really say for sure.

Best,
Kevin
