### ISSUE TITLE
"scaden example --out example_data/" doesn't work

### ISSUE THREAD

**Issue by bioinfouser** [KevinMenden/scaden#72]
Hello Kevin,

After installing scaden via pip(I am using macOS), I tried running it for the example data, but it gives error saying:

Error: No such command 'example'.

Could you suggest why this is happening?

**Comment by KevinMenden** [comment]
Hi,

hmm that shouldn't be happening.
Can you quickly check that you have a recent version, using:
`scaden --version` 

And if you type in scaden, do you see something like this:

```
     ____                _            
    / ___|  ___ __ _  __| | ___ _ __  
    \___ \ / __/ _` |/ _` |/ _ \ '_ \ 
     ___) | (_| (_| | (_| |  __/ | | |
    |____/ \___\__,_|\__,_|\___|_| |_|

    
Usage: scaden [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  example
  predict   Predict cell type composition using a trained Scaden model
  process   Process a dataset for training
  simulate  Create artificial bulk RNA-seq data from scRNA-seq dataset(s)
  train     Train a Scaden model

```

Meaning, does it list 'example' as command?
