### ISSUE TITLE
Availability of sc-rnaseq data

### ISSUE THREAD

**Issue by Klopfe** [KevinMenden/scaden#75]
Hi, 
I would like to know if the sc-rnaseq (already clustered and labeled) given to CibersortX for example on 6k PBMC and 8k PBMC are available somewhere ?
Thanks for your article and your great work.

**Comment by KevinMenden** [comment]
Sorry for the late reply!

I'm afraid I don't have that data anymore. If you want to generate data for CIBERSORTx, it should be relatively straight forward to process the 10X genomics PBMC datasets for that.
