### ISSUE TITLE
Bump conda

### ISSUE THREAD

**Issue by khkk378** [KevinMenden/scaden#86]
Hi! Would you consider bumping the bioconda package? It doesn't really fit the documentation anymore. Thanks!

Cheers,
Rasmus

**Comment by KevinMenden** [comment]
hi @khkk378 ,

do you need the bioconda package, or can you use pip instead? (can still install inside a conda environment)
There are some issues with the bioconda recipe that I could not solve. I have mentioned this in the documention somewhere. Probably I should remove the mention of bioconda altogether for now...

**Comment by khkk378** [comment]
Conda is so convenient, so it you can get it to work it would be welcome :) Otherwise I think drop it, because it's confusing as is now when the documentation doesn't match the functionality. I tried installing with pip, but for some reason it started to download every single version of numpy. I will use conda and for your dependencies and then just install scaden with pip.
