### ISSUE TITLE
Pattern not matching in scaden simulate

### ISSUE THREAD

**Issue by khkk378** [KevinMenden/scaden#87]
If I run `scaden simulate --data somedir` but also have files matching the pattern in the working dir I get the error `No datasets found! Have you specified the pattern correctly?`. In my case it was because I had the output from `scaden example` in the working dir.

**Comment by KevinMenden** [comment]
Hi @khkk378 , thanks for reporting!

I'll have a look at it when I get around to it. In the meantime, could you specify a bit more what you have done?

**Comment by khkk378** [comment]
I have the files `somedir/foo_counts.txt` and `somedir/foo_celltypes.txt` that I want to simulate from. I also have the files `example_counts.txt` and `example_celltypes.txt`. If I run `scaden simulate --data somedir --pattern *_counts.txt` I get the error. If I remove `example_*.txt` it works. I would assume that the pattern should be applied to the files in the `--data` dir.

**Comment by KevinMenden** [comment]
Huh, interesting ... that's really odd indeed 🤔 will look into this and let you know! 

You're right that the pattern should be applied the data in `--data`

**Comment by KevinMenden** [comment]
Could you enclose the pattern in brackets, like '*_counts.txt'  and try again, please?
