### ISSUE TITLE
M256 drop out rates in M1024

### ISSUE THREAD

**Issue by khkk378** [KevinMenden/scaden#88]
Hi!

You're using the M256 DO rates in M1024. Is this on purpose?

```
cdn1024 = Scaden(
        model_dir=model_dir + "/m1024",
        model_name="m1024",
        seed=seed,
        hidden_units=M1024_HIDDEN_UNITS,
        do_rates=M256_DO_RATES,
    )
```

**Comment by KevinMenden** [comment]
Hi Rasmus, 

thanks for reporting! No that's not on purpose and a bug :) I refactored this part of the code recently, where I must have introduced this :facepalm: 

Fortunately it doesn't matter, as this is the model used for prediction and dropout is deactivated during prediction. Nevertheless, not good. Will fix it!

**Comment by KevinMenden** [comment]
Will probably get out a new release this evening because that's rather annoying.
