### ISSUE TITLE
singularity image or environment.yml

### ISSUE THREAD

**Issue by nfancy** [KevinMenden/scaden#96]
Hi, 

Thank you for this great package. I recently tried your package for deconvolution and want to use it on our HPC. However, as hpc does not allow us to use docker image, a singularity image is an alternative option. Is it possible for your to upload your dokcer image to docker up as singularity can convert image from docker hub into singularity image. I tried singularity with ghro.io but the image is not working. Another option of course is to use conda environment. I successfully installed scaden using conda but I am always getting one or the other error probably related to the versions of the dependencies. Is it possible for you to share the envirnoment.yml file for conda? 

Thanks in advance.
Nurun

**Comment by nfancy** [comment]
hi, bumping this for a response. Thanks again.

update: I found your docker image from dockerhub and could convert it to a singularity image, however, the issue remains because the image in dockerhub does not contain the simulate function which is my main bottleneck. To simulate bulk from snRNAseq dataset.

**Comment by KevinMenden** [comment]
Hi,

sorry for the late reply, I was on vacation. The docker image on dockerhub is outdated. I'm not very used to singularity but maybe you can download the docker image and convert to singularity locally?

Alternatively, here is the bioconda recipe, it has all the dependencies in it:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/scaden/meta.yaml

Best,
Kevin
