### ISSUE TITLE
scaden train can't find key 'cell_types'

### ISSUE THREAD

**Issue by sydneysue** [KevinMenden/scaden#98]
Hi Kevin,

I was finally able to install scaden and was able to run the preprocessing step smoothly. However, when I tried using scaden train, I ran into this error:
`KeyError: 'cell_types'`

I believe this is coming from the line:
`ratios = [raw_input.obs[ctype] for ctype in raw_input.uns["cell_types"]]`

Do you know how I might be able to fix this? 

Thanks for your help!

Sydney

**Comment by KevinMenden** [comment]
Hi Sydney,

could you explain a bit what data you used and what commands you  used before using `scaden train` ?

Thanks!

Kevin

**Comment by KevinMenden** [comment]
Hi Sydney,

the `cell_types` field is added to `.uns` during the `scaden simulate` step - so I'm assuming you skipped that step?
That would explain the problem :) 

Kevin

**Comment by sydneysue** [comment]
Ah, that makes sense! Thank you so much!

**Comment by sydneysue** [comment]
Hi Kevin,

I preprocessed my single-cell data according to your scripts and used the normalized data as input for the `scaden simulate` and ran this step using the same parameters given in the documentation. I got the resulting data.h5ad, however when I tried to run `scaden process`, I ran into an error during the Max/Min process where some of my values were infinite. Is there a way to fix this?

Thank you!

Sydney

**Comment by KevinMenden** [comment]
Hi Sydney,

ah that is a bug that I seem to have introduced recently, by trying to making it all more memory efficient 🤦 

It's already fixed in the `development` branch, so you could install from there. I will make a new bug-fix release though. Didn't think that this is such a problem.

Sorry for the inconvenience!

Best,
Kevin

**Comment by KevinMenden** [comment]
I made a new release now - the new version should be available from PyPi in a bit. 

Recently bioconda started to work as well again

**Comment by sydneysue** [comment]
Thank you! I was able to run through everything smoothly!
